excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://herocoda.github.io
title: Herocoda
tagline: Blog sur l'actualité web
description: My awesome new site
paginate: 5
highlighter: rouge
