excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://herocoda.github.io
title: Herocoda
tagline: Développement web et dernières technologies du web
description: Blog perso consacré à l’actualité web/internet, jeux-vidéos mais aussi à des notes ou documents. Fait par @Aurelien
paginate: 5
highlighter: rouge
