excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://herocoda.github.io
title: Herocoda
tagline: Développement web et dernières technologies du web
description: Blog perso consacré à l’actualité web/internet, mais aussi à des documents ou mes notes perso. @Aurelien
paginate: 5
highlighter: rouge
