excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://herocoda.github.io
title: Herocoda
tagline: Développement web et dernières technologies du web
description: My awesome new site
paginate: 5
highlighter: rouge
